### ISSUE TITLE
New post notification redirects to blank screen

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#137]
Reposted by Arava

**Comment by watchtower314** [comment]
The discussion cannot be found, even though it exists in the database, this also happens with other notifications
<img width="555" alt="Screen Shot 2021-02-28 at 12 35 30" src="https://user-images.githubusercontent.com/30501647/109427673-76941f80-79c1-11eb-84dd-005184a430ad.png">

**Comment by watchtower314** [comment]
This was fixed in Lyubo's pr: https://github.com/daostack/common/pull/954

**Comment by yanivi71** [comment]
@watchtower314 that is still happens. 
sometime it redirect to the correct position and sometime i get white screen

**Comment by watchtower314** [comment]
This is caused due to `navigationRef.current` that is undefined, hence cannot dispatch navigation
same as https://github.com/daostack/common-monorepo/issues/74

**Comment by watchtower314** [comment]
Duplicate: https://github.com/daostack/common-monorepo/issues/137
Closing this
